Commit message
ilyakolbafk/reactjs pull request #3
Opened 2020-10-15 14:22 UTC by ilyakolbafk

Колб Илья

2020-10-15 14:23 UTC, ilyakolbafk commented
@valerystatinov

2020-10-15 14:38 UTC, ValeryStatinov commented
пригласите меня в коллабораторы проекта, см на гитхабе курса как это делать

2020-10-15 14:51 UTC, ilyakolbafk commented
> пригласите меня в коллабораторы проекта, см на гитхабе курса как это делать

Я вас добавлял. 
<img width="950" alt="Снимок экрана 2020-10-15 в 17 51 33" src="https://user-images.githubusercontent.com/72526625/96146545-11a6c400-0f0f-11eb-8b1c-f41a0bb4ca3e.png">

2020-10-18 14:28 UTC, ValeryStatinov requested changes

2020-10-18 14:28 UTC, ValeryStatinov commented on src/App.js
> +                {this.state.tasks.map(task => new Element(task))}
если `Element` был бы классовым компонентом со стейтом, то при ререндере `MyTodoList` стейт каждого задания терялся бы и сбрасывался на начальный. нужно "рисовать" компонент, а не создавать новый на каждом рендере.
`{this.state.tasks.map(task => <Element task={task} />)}`

2020-10-18 14:37 UTC, ValeryStatinov requested changes
случайно сам перезапросил)

2020-10-24 21:29 UTC, ilyakolbafk commented
не туда нажал

2020-10-24 21:33 UTC, closed without merging